### ISSUE TITLE
Data?

### ISSUE THREAD

**Issue by rick-osmo** [chemosim-lab/M2OR#1]
Hi,

I spoke with you at your poster at AChemS.   Will the data for M2OR be put into this repository?

**Comment by Maxence-Lalis** [comment]
Hello,

Data is now available and named “M2OR_20230428.csv”. I will add more and update the repo in the near future.

**Comment by seyonechithrananda** [comment]
Do you know where we can find the post-processed, binarized data (accounting for different types of experiments for each pair, etc) used to train the protein-ligand model?

**Comment by seyonechithrananda** [comment]
^ i've looked through the raw data and have a vague understanding of how the filtering was done, but was wondering if there was a frozen post-processed dataframe of mol-OR pairs for the 04/28/23 data release?

**Comment by MatejHl** [comment]
Hello all,

I come back to this thread in case someone will come to look for the data through here. 

The most up-to-date data are available on the M2OR website: [https://m2or.chemsensim.fr/](https://m2or.chemsensim.fr/)
This repository will be updated with (possibly large) delay, so preferably check the data on the website which is up to date.

I wish you a happy research!
     Matej
